# Generated by Django 2.1.1 on 2019-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190729_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('good_pirce', models.FloatField(verbose_name='商品价格')),
                ('good_total', models.FloatField(verbose_name='商品总价')),
                ('good_number', models.IntegerField(verbose_name='商品数量')),
                ('good_image', models.FileField(upload_to='buyer/images', verbose_name='商品图片')),
                ('good_id', models.IntegerField(verbose_name='商品ID')),
                ('good_store', models.IntegerField(verbose_name='商品店铺')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
            ],
        ),
    ]
