# Generated by Django 2.1.1 on 2019-07-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='good_pirce',
            new_name='good_price',
        ),
    ]
