# Generated by Django 2.1.1 on 2019-07-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_state',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_image',
            field=models.ImageField(upload_to='store/images', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
    ]
